OBMC_IMAGE_EXTRA_INSTALL:append = " mboxd \
    webui-vue \
    net-snmp-server-snmpd \
    net-snmp-server-snmptrapd \
    net-snmp \
    snmp \
    phosphor-pid-control \
    phosphor-ipmi-kcs \
    record-data \
    curl \
    sqlite3 \
    srvcfg-manager \
    fru-eeprom \
    phosphor-hostlogger \
    bind-sensor \
    bios-update \
    ipmitool \
    loadsvf \
    onbd \
    gpio-power "
